controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    base_controller:
      type: diff_drive_controller/DiffDriveController
    safety_controller:
      type: forward_command_controller/ForwardCommandController
